// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANCVEhFQFlOQpBRnmUx_aHmVhZr_rA3DM',
    appId: '1:580697236187:web:402b4eec5b3a965a6562fe',
    messagingSenderId: '580697236187',
    projectId: 'materialcampus-11',
    authDomain: 'materialcampus-11.firebaseapp.com',
    storageBucket: 'materialcampus-11.appspot.com',
    measurementId: 'G-4V34D4DWX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMEshQtyF97qNIgnQr8Jo4oZoJP_wNdXw',
    appId: '1:580697236187:android:43d84a715b9b82aa6562fe',
    messagingSenderId: '580697236187',
    projectId: 'materialcampus-11',
    storageBucket: 'materialcampus-11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkoecony9-K2xsRlU1N78oFtO17VcB1LU',
    appId: '1:580697236187:ios:51099de765405f846562fe',
    messagingSenderId: '580697236187',
    projectId: 'materialcampus-11',
    storageBucket: 'materialcampus-11.appspot.com',
    iosBundleId: 'com.example.materialCampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkoecony9-K2xsRlU1N78oFtO17VcB1LU',
    appId: '1:580697236187:ios:51099de765405f846562fe',
    messagingSenderId: '580697236187',
    projectId: 'materialcampus-11',
    storageBucket: 'materialcampus-11.appspot.com',
    iosBundleId: 'com.example.materialCampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANCVEhFQFlOQpBRnmUx_aHmVhZr_rA3DM',
    appId: '1:580697236187:web:b3185c06bc04c4a26562fe',
    messagingSenderId: '580697236187',
    projectId: 'materialcampus-11',
    authDomain: 'materialcampus-11.firebaseapp.com',
    storageBucket: 'materialcampus-11.appspot.com',
    measurementId: 'G-H9TC59QQMZ',
  );
}
